name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Отримання коду
        uses: actions/checkout@v2

      - name: Встановлення JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Збірка
        run: mvn clean install

      - name: Розгортання
        run: echo "Розгортання завершено."
